kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-config
data:
  corsOrigin: {{ .Values.settings.config.corsOrigin | toString | b64enc }}
  botGrpcUrl: {{ .Values.settings.config.botGrpcUrl | toString | b64enc }}