kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-config
data:
  botGrpcUrl: {{ .Values.settings.config.botGrpcUrl | toString }}
  botAdminPanelUrl: {{ .Values.settings.config.botAdminPanelUrl | toString }}