apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database
data:
  databaseUrl: {{ .Values.settings.database.url | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-discord
data:
  applicationId: {{ .Values.settings.discord.applicationId | toString | b64enc }}
  botToken: {{ .Values.settings.discord.botToken | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-jwt
data:
  jwtSecret: {{ .Values.settings.jwt.secret | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-openai
data:
  apiKey: {{ .Values.settings.openai.apiKey | toString | b64enc }}