apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-general
data:
  logLevel: {{ .Values.settings.general.logLevel | toString | b64enc }}
  apiToken: {{ .Values.settings.general.apiToken | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database
data:
  databaseUrl: {{ .Values.settings.database.url | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-discord
data:
  applicationId: {{ .Values.settings.discord.applicationId | toString | b64enc }}
  botToken: {{ .Values.settings.discord.botToken | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth0
data:
  domain: {{ .Values.settings.auth0.domain | toString | b64enc }}
  clientId: {{ .Values.settings.auth0.clientId | toString | b64enc }}
  audience: {{ .Values.settings.auth0.audience | toString | b64enc }}