kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-discordbot-config
data:
  botAdminPanelUrl: {{ .Values.settings.config.botAdminPanelUrl | toString }}
  rabbitmqURI: {{ .Values.settings.config.rabbitmqURI | toString }}