apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-discordbot-database
data:
  databaseUrl: {{ .Values.settings.database.url | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-discordbot-discord
data:
  applicationId: {{ .Values.settings.discord.applicationId | toString | b64enc }}
  botToken: {{ .Values.settings.discord.botToken | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-discordbot-openai
data:
  apiKey: {{ .Values.settings.openai.apiKey | toString | b64enc }}