apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database
data:
  databaseUrl: {{ .Values.settings.database.url | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-jwt
data:
  jwtSecret: {{ .Values.settings.jwt.secret | toString | b64enc }}
