apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api-database
data:
  databaseUrl: {{ .Values.settings.database.url | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api-jwt
data:
  jwtSecret: {{ .Values.settings.jwt.secret | toString | b64enc }}
